[build]
  command = "rm -rf .next && npx prisma generate && npm run build"
  publish = ".next"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_STRIPE_PRICE_MAX,NEXT_PUBLIC_STRIPE_PRICE_PRO,NEXT_PUBLIC_STRIPE_PRICE_BASIC,STRIPE_WEBHOOK_SECRET,NEXTAUTH_URL"
  NODE_VERSION = "20"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = [
    "!node_modules/.prisma/client/libquery_engine-*",
    "!node_modules/.prisma/client/query_engine*",
    "!node_modules/@prisma/engines/**",
    "!node_modules/pdf-parse/test/**",
    "!node_modules/typescript/**",
    "!node_modules/@next/swc*",
    "!node_modules/next/dist/compiled/webpack*"
  ]

[functions."sync-background"]
  node_bundler = "nft"
